### ISSUE TITLE
Establish an environment where Lambda can run locally

### ISSUE THREAD

**Issue by keita-nishimoto** [keita-nishimoto/aws-serverless-prototype#50]
## Done
- It meets the condition of the title

**Comment by keita-nishimoto** [comment]
Posted an https://github.com/99xt/serverless-dynamodb-local/issues/70.

Until https://github.com/99xt/serverless-dynamodb-local/issues/70 is resolved, install "DynamoDB" on your own.

**Comment by keita-nishimoto** [comment]
https://github.com/keita-nishimoto/aws-lambda-ansible/issues/19 を作成。
この課題の中でDynamoDBのローカル環境を整える。

**Comment by keita-nishimoto** [comment]
```
Serverless: Running Authorization function for post /clients (λ: authorization)
{ [Error: Cannot find module '/home/vagrant/aws-serverless-prototype/auth'] code: 'MODULE_NOT_FOUND' }
Debug: internal, implementation, error
    Error: Internal Server Error
    at Object.authenticate (/home/vagrant/aws-serverless-prototype/node_modules/serverless-offline/src/createAuthScheme.js:52:27)
    at /home/vagrant/aws-serverless-prototype/node_modules/hapi/lib/auth.js:324:34
    at [object Object].internals.Protect.run.finish [as run] (/home/vagrant/aws-serverless-prototype/node_modules/hapi/lib/protect.js:64:5)
    at [object Object].execute (/home/vagrant/aws-serverless-prototype/node_modules/hapi/lib/auth.js:320:30)
    at [object Object].authenticate (/home/vagrant/aws-serverless-prototype/node_modules/hapi/lib/auth.js:306:21)
    at [object Object].internals.Auth.test.internals.Auth._authenticate (/home/vagrant/aws-serverless-prototype/node_modules/hapi/lib/auth.js:214:19)
    at internals.Auth.test.internals.Auth.authenticate (/home/vagrant/aws-serverless-prototype/node_modules/hapi/lib/auth.js:202:17)
    at each (/home/vagrant/aws-serverless-prototype/node_modules/hapi/lib/request.js:384:16)
    at iterate (/home/vagrant/aws-serverless-prototype/node_modules/items/lib/index.js:36:13)
    at done (/home/vagrant/aws-serverless-prototype/node_modules/items/lib/index.js:28:25)
    at internals.state.next (/home/vagrant/aws-serverless-prototype/node_modules/hapi/lib/route.js:357:16)
    at each (/home/vagrant/aws-serverless-prototype/node_modules/hapi/lib/request.js:384:16)
    at iterate (/home/vagrant/aws-serverless-prototype/node_modules/items/lib/index.js:36:13)
    at Object.exports.serial (/home/vagrant/aws-serverless-prototype/node_modules/items/lib/index.js:39:9)
    at [object Object].internals.Request.internals.Request._execute.internals.Request._lifecycle.each [as _lifecycle] (/home/vagrant/aws-serverless-prototype/node_modules/hapi/lib/request.js:387:11)
    at [object Object].internals.Request.internals.Request._execute (/home/vagrant/aws-serverless-prototype/node_modules/hapi/lib/request.js:302:21)
    at Domain.<anonymous> (/home/vagrant/aws-serverless-prototype/node_modules/hapi/lib/connection.js:261:25)
    at Domain.run (domain.js:228:14)
    at [object Object].internals.Protect.run.internals.Protect.enter (/home/vagrant/aws-serverless-prototype/node_modules/hapi/lib/protect.js:80:17)
    at Server.<anonymous> (/home/vagrant/aws-serverless-prototype/node_modules/hapi/lib/connection.js:259:30)
    at emitTwo (events.js:87:13)
    at Server.emit (events.js:172:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:537:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:97:23)
```

**Comment by keita-nishimoto** [comment]
```serverless-webpack```であればローカルで実行する事は可能。
ただし認可ロジックは呼ばれない模様。

やはり```serverless-offline```での実行が可能になるまで調査を進めるしかないか。

**Comment by keita-nishimoto** [comment]
```node_modules/serverless-offline/src/createAuthScheme.js 46```  に以下のコードを追加したらとりあえず動かす事は出来た。。。

```
funOptions.handlerPath = '/home/vagrant/aws-serverless-prototype/.webpack/auth.js';
```

しかしこれで良い訳がないので何とかしてfunOptions.handlerPathに値を設定する方法を調査する。

**Comment by keita-nishimoto** [comment]
https://github.com/keita-nishimoto/aws-lambda-ansible/pull/20

**Comment by keita-nishimoto** [comment]
少々遠回りだが ```serverless-webpack``` でも認可ロジックをテストする事は可能。
以下の条件を満たす必要がある。

- HTTPSのエンドポイントを作成する
- event.authorizationTokenから値が取れない場合にheaders.Authorizationから参照する
- event.methodArnが存在しない場合にrequestContextを駆使して対象リソースのARNを組み立てる

```serverless-offline``` をTypeScriptで正常動作させるのはコストがかかるので今はこの方法で対応する。

ただ最終的にはより良いローカル環境にしたいので https://github.com/keita-nishimoto/aws-serverless-prototype/issues/55 で本格対応を行う。

**Comment by keita-nishimoto** [comment]
この方法が使えるか試してみる。
http://qiita.com/teradonburi/items/3ab06f04edbdbdcb02a7

**Comment by keita-nishimoto** [comment]
APIの認可ロジックだがローカルでは結合テストをしない方針とする。
理由は以下の通り。

- ローカル実行時とリモートでの実行時で渡ってくるeventオブジェクトの形が違いすぎる為、結局リモートで動作させないと動作を担保出来ているとは言い難い為。

- ローカルでテストするにはあらゆる場所にローカル実行かどうかの判定処理を入れなければならず、かなり効率が悪い。

AccessTokenRepositoryの単体テストで済ませておくのが無難。
